config/routes.rb
Rails.application.routes.draw do
  # get 'follows/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "offers#index"
  get "/map", to: "pages#map"
  get "/landing", to: "offers#landing"

  devise_for :users

  resources :chatrooms, only: %i[index show new create] do
    resources :messages, only: :create
  end

  resources :bookings, except: %i[new create] do
    resources :reviews
  end

  resources :offers do
    resources :bookings, only: %i[new create]
  end

  resources :dashboard, only: [:index] do
    resources :offers, only: %i[edit update destroy]
    resources :bookings, only: %i[edit update destroy]
    # patch 'offers/:id/update', to: 'dashboard#update_offer', as: :update_offer
    # delete 'offers/:id/delete', to: 'dashboard#delete_offer', as: :delete_offer
    patch 'bookings/:id/accept', to: 'dashboard#accept_booking', as: :accept_booking
    # patch 'bookings/:id/reject', to: 'dashboard#reject_booking', as: :reject_booking
    # patch 'bookings/:id/confirm', to: 'dashboard#confirm_booking', as: :confirm_booking
  end

  get "profiles/:id", to: "pages#profiles", as: 'profile'
  post 'profiles/:id', to: "pages#createprofile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :offers
  # has_many :reviews
  has_many :followers
  has_many :chatrooms
  has_many :messages
  has_many :bookings
  has_one_attached :profile_picture

  has_many :reviews, foreign_key: :reviewer_id
  has_many :received_reviews, foreign_key: :reviewee_id, class_name: "Review"
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @offers = current_user.offers
    @bookings = current_user.bookings
  end

  def update_offer
    @offer = Offer.find(params[:id])
    redirect_to dashboard_path
  end

  def delete_offer
    @offer = Offer.find(params[:id])
    offer.destroy
    redirect_to dashboard_path
  end

  def accept_booking
    @booking = Booking.find(params[:id])
    @booking.booking_status.update(accepted: true)
    redirect_to dashboard_path
  end

  def reject_booking
    @booking = Booking.find(params[:id])
    @booking.booking_status.destroy
    redirect_to dashboard_path
  end

  def confirm_booking
    @booking = Booking.find(params[:id])
    @booking.booking_status.update(completed: true)
    redirect_to dashboard_path
  end
end

app/views/dashboard/_bookingcard.html.erb
<div class="offer-card">
  <div class="right-content">
    <div class="padding-wrapper">
      <p><%= booking.offer.typeofoffer ?  booking.offer.typeofoffer : "Vegan" %></p>
        <h6><%= booking.offer.title[0...20] %></h6>
        <p><%= booking.offer.address[0...20] %></p>
        <p><i class="fa-regular fa-clock"></i> <%= booking.offer.pickupslots %></p>

    <div class="placeholder-offer-card">
      <%= link_to booking_path(booking.id), data: {turbo_method: :delete} do %>
        <i class="fa-regular fa-trash-can"></i>
        <% end %>
      <%= link_to chatroom_path(Chatroom.find_by(booking_id: booking.id)) do %>
        <i class="fa-regular fa-message"></i>
        <% end %>
      <%= link_to new_booking_review_path(booking) do %>
        <i class="fa-regular fa-star"></i>
      <% end %>
    </div>


    </div>
  </div>

   <div class="left-image">
    <% if booking.offer.images.attached? %>
      <% booking.offer.images.each do |photo| %>
      <%= cl_image_tag photo.key,
        :gravity => "center",
        :class => "dashboard-img", crop: :fill %>
    <% end %>
    <% else %>
      <h5>PlaceHolder</h5>
    <% end %>
   </div>


</div>

app/views/dashboard/_offercard.html.erb
<div class="offer-card">
  <div class="right-content">
    <div class="padding-wrapper">
      <p><%= offer.typeofoffer ?  offer.typeofoffer : "Vegan" %></p>
        <h6><%= offer.title[0...20] %></h6>
        <p><%= offer.address[0...20] %></p>
        <p><i class="fa-regular fa-clock"></i> <%= offer.pickupslots %></p>

    <div class="placeholder-offer-card">
      <%= link_to offer_path(offer.id), data: {turbo_method: :delete} do %>
        <i class="fa-regular fa-trash-can"></i>
      <% end %>
      <%= link_to edit_offer_path(offer.id) do %>
        <i class="fa-solid fa-pencil"></i>
      <% end %>
       <%= link_to edit_offer_path(offer.id) do %>
        <i class="fa-regular fa-eye"></i>
      <% end %>
      <% unless Booking.find_by(offer_id: offer.id).nil? %>
        <%= link_to chatroom_path(Chatroom.find_by(booking_id: Booking.find_by(offer_id: offer.id).id)) do %>
          <div class="booked-received">
          <i class="fa-regular fa-message"></i>
          <p>Order Booked</p>
          </div>
        <% end  %>
      <% end %>
    </div>


    </div>
  </div>

   <div class="left-image">
    <% if offer.images.attached? %>
      <% offer.images.each do |photo| %>
      <%= cl_image_tag photo.key,
        :gravity => "center",
        :class => "dashboard-offercard_image", crop: :fill %>
      <% end %>
    <% else %>
      <h5>PlaceHolder</h5>
    <% end %>
   </div>


</div>

app/views/dashboard/index.html.erb
<div class="dashboard-title-offer">
  <h3>My Offers</h3>
  <% @offers.each do |offer| %>
    <%= render "offercard", offer: offer %>
  <% end %>
</div>


<div class="dashboard-title-booking">
  <h3>My bookings</h3>
  <% @bookings.each do |booking| %>
    <%= render "bookingcard", booking: booking %>
  <% end %>
</div>


<div class = "blankline"> </div>

app/views/dashboard/m_temp.html.erb
<div class="dashboard-offerheader">
  <div>
    <% if current_user.profile_picture.attached? %>
        <%= cl_image_tag current_user.profile_picture.key,
          :gravity => "center",
          :class => "avatar-square",
          crop: :fit %>
        <% else %>
          <img src="https://res.cloudinary.com/dxdyu4tqu/image/upload/v1683908905/profile_pictures/photo-1583795128727-6ec3642408f8.jpg" alt="", class= "avatar-bordered">
        <% end %>
  </div>
  <div class="dashboard-userinfo">
    <span class="dashboard-username">Hello @<%= current_user.username %></span>
    <span class="dashboard-details"><i class="fa-solid fa-location-arrow arrow"></i> <%= current_user.address.split(",")[-4..-2].join %></span>
    <span class="dashboard-details">Rating <%= current_user.reviews[0] %></span>
  </div>
</div>


<div class = "dashboard-offercard-container">

  <div class= "dashboard-img-container">
    <% if offer.images.attached? %>
      <% offer.images.each do |photo| %>
      <%= cl_image_tag photo.key,
        :gravity => "center",
        :width => 150,
        :height => 150,
        :class => "dashboard-offercard_image", crop: :fill %>
    <% end %>
    <% else %>
      <h5>PlaceHolder</h5>
    <% end %>
  </div>

  <div class = "dashboard-offer-container">
    <p>Title: <%= offer.title %></p>
    <%# <p>Description: <%= offer.body %></p> %>
   ≈
    <p>Available pickup slots: <%= offer.pickupslots %></p>
    <p>Type of food: <%= offer.typeofoffer %></p>
    <p>Allergens: <%= offer.allergen %></p>
    <p>Created at: <%= time_ago_in_words(offer.created_at) %></p>
    <p>Booked?:<%= offer.booking_ids.blank? %></p>
    <!-- Display other offer details -->
    <%= link_to 'edit', edit_offer_path(offer) %>
    <%= link_to 'Delete', offer_path(offer), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%#= link_to 'Accept Booking', dashboard_accept_booking_path(offer.booking) %>
    <!-- Display other offer actions -->

  </div>


</div>




_bookingcard(old one)



<div class = "dashboard-offercard-container">

  <div class= "dashboard-img-container">
    <% if booking.offer.images.attached? %>
      <% booking.offer.images.each do |photo| %>
      <%= cl_image_tag photo.key,
        :gravity => "center",
        :width => 150,
        :height => 150,
        :class => "dashboard-offercard_image", crop: :fill %>
    <% end %>
    <% else %>
      <h5>PlaceHolder</h5>
    <% end %>
  </div>

  <div class = "dashboard-offer-container">
    <p>Title: <%= booking.offer.title %></p>
    <p>Status: <%= booking.offer.body %></p>
    <!-- Display other booking details -->
    <%#= link_to 'edit', edit_offer_path(offer) %>
    <%#= link_to 'Delete', offer_path(offer), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%#= link_to 'Accept Booking', dashboard_accept_booking_path(offer.booking) %>
    <!-- Display other offer actions -->

  </div>


</div>




murilo code

<div class="booking-card">
  <div class="right-content">
    <div class="padding-wrapper">
        <p><i class="fa-regular fa-clock"></i> <%= booking.pick_up_time %></p>

      <div class="placeholder-booking-card">
        <%= link_to booking_path(booking.id), data: {turbo_method: :delete} do %>
          <i class="fa-regular fa-trash-can"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class= "dashboard-img-container">
    <% if booking.offer.images.attached? %>
      <% booking.offer.images.each do |photo| %>
        <%= cl_image_tag photo.key,
          :gravity => "center",
          :width => 150,
          :height => 150,
          :class => "dashboard-offercard_image", crop: :fill %>
      <% end %>
    <% else %>
      <h5>PlaceHolder</h5>
    <% end %>
  </div>
</div>