config/routes.rb
Rails.application.routes.draw do
  # get 'follows/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "offers#index"
  get "/map", to: "pages#map"
  get "/landing", to: "offers#landing"

  devise_for :users

  resources :chatrooms, only: %i[index show new create] do
    resources :messages, only: :create
  end

  resources :bookings, except: %i[new create] do
    resources :reviews
  end

  resources :offers do
    resources :bookings, only: %i[new create]
  end

  resources :dashboard, only: [:index] do
    resources :offers, only: %i[edit update destroy]
    resources :bookings, only: %i[edit update destroy]
    # patch 'offers/:id/update', to: 'dashboard#update_offer', as: :update_offer
    # delete 'offers/:id/delete', to: 'dashboard#delete_offer', as: :delete_offer
    patch 'bookings/:id/accept', to: 'dashboard#accept_booking', as: :accept_booking
    # patch 'bookings/:id/reject', to: 'dashboard#reject_booking', as: :reject_booking
    # patch 'bookings/:id/confirm', to: 'dashboard#confirm_booking', as: :confirm_booking
  end

  get "profiles/:id", to: "pages#profiles", as: 'profile'
  post 'profiles/:id', to: "pages#createprofile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-3 mb-5 rounded-3 shadow-sm" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-3 mb-5 rounded-3 shadow-sm" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footnavbar.html.erb
<div data-filter-target="profileiconcontainer" class="profileicon-container hiddennav">
<div class = "blurring-bottomfilter" ></div>
  <% if user_signed_in? %>
    <div class="button-div profile">
    <%= link_to dashboard_index_path do %>
      <div class="button-items">
          <i class="bi bi-ui-checks-grid"></i>
          <span class = "navbar-text">Dashboard</span>
      </div>
    <% end %>
    </div>

    <div class="button-div profile">
    <%= link_to edit_user_registration_path do %>
      <div class="button-items">
          <i class="bi bi-pencil-square"></i>
          <span class = "navbar-text">EditUser</span>
      </div>
    <% end %>
    </div>

    <div class="button-div profile">
    <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
      <div class="button-items">
          <i class="bi bi-box-arrow-right"></i>
          <span class = "navbar-text">LogOut</span>
      </div>
    <% end %>
    </div>

  <% else %>
    <div class="button-div">
    <%= link_to new_user_session_path do %>
      <div class="button-items">
          <i class="bi bi-box-arrow-in-right"></i>
          <span class = "navbar-text">Login</span>
      </div>
    <% end %>
    </div>

    <div class="button-div">
    <%= link_to new_user_registration_path do %>
      <div class="button-items">
          <i class="bi bi-person-plus"></i>
          <span class = "navbar-text">Register</span>
      </div>
    <% end %>
  </div>
  <% end %>
</div>


<div class="footnavbar">
  <div class="button-div">
    <%= link_to root_path do %>
    <div class="button-items">
        <i class="bi bi-columns-gap"></i>
        <span class = "navbar-text">Home</span>
    </div>
    <% end %>
  </div>

  <div class="button-div">
    <%= link_to map_path do %>
    <div class="button-items">
      <i class="bi bi-compass"></i>
      <span class = "navbar-text">Map</span>
    </div>
    <% end %>
  </div>

  <div class="button-div">
    <%= link_to new_offer_path do %>
    <div class="button-items">
      <i class="bi bi-plus-circle"></i>
      <span class = "navbar-text">Add offer</span>
    </div>
    <% end %>
  </div>

  <div class="button-div"  data-controller="unread-messages">
    <%= link_to chatrooms_path do %>
    <div class="button-items">
      <i class="bi bi-chat-left"></i>
      <span class = "navbar-text">Messages</span>
      <%# <div class="unread-messages-box" data-controller="unread-messages"
      </div> %>
      <div class="unread-messages-box" id="unread-messages-box" data-unread-messages-target="count">
        <%= unread_messages() %>
      </div>
    </div>
    <% end %>
  </div>

  <div class="button-div">
    <div class="button-items" data-action="click->filter#toggleProfileicon">
          <% if current_user && current_user.profile_picture.attached? %>
              <%= cl_image_tag current_user.profile_picture.key,
                :gravity => "center",
                :width => 50,
                :height => 50,
                :class => "avatar-bordered-profile",
                :crop => :fill %>
              <% else %>
                <img src="https://res.cloudinary.com/dxdyu4tqu/image/upload/v1683908905/profile_pictures/photo-1583795128727-6ec3642408f8.jpg" alt="", class= "avatar-bordered-profile">
          <% end %>
        <span class = "navbar-text user">User</span>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="search-bar-frame" data-controller="supersearchbar">
  <%= form_with url: root_path, method: :get, class: "d-flex search-box" do %>
    <div class="input-group">
      <%= text_field_tag :query,
            params[:query],
            class: "form-control search-form",
            placeholder: "Search...",
            data: {supersearchbar_target: "input"}
        %>
      <div class="search-cancel-button">
        <button  class="btn btn-light" data-supersearchbar-target="button" data-action="click->supersearchbar#clickMe">
          <i class="fa-solid fa-circle-xmark"></i>
        </button>
      </div>
    </div>
    <%= hidden_field_tag :search_submit, "true" %>
  <% end %>
  <div class="dropdown">
    <button type="button" class="btn btn-transparent" >
      <i class="bi bi-sliders" data-action="click->filter#toggleFilter" ></i>
    </button>
  </div>
</div>

<%# IN CASE WE WOULD LIKE TO ACTIVATE THE FILTERS FUNCTIONALITIES WE NEED TO CANCEL OUT ALL THE COMMENTS BELOW AND START CODING FROM THERE%>

<div data-filter-target="filtercontainer" data-action="click->filter-controller#toggleFilter"   class="filter-container hiddennavsearch">
  <div class = "blurring-topfilter" ></div>
  <div class="filters-content">
    <h6>Food Type</h6>
      <div class="checkboxes-container">
        <div class="btn-group btnrounded" role="group" aria-label="Basic radio toggle button group">

          <%# <form action="offers"> %>
            <input type="radio" class="btn-check" name="filter" id="btnradio1" autocomplete="off" checked>
            <%# <input type="hidden" name="filter" id="btnradio1" value="vegan"> %>
            <label class="btn btn-outline-dark" for="btnradio1">Vegan</label>
          <%# </form> %>

          <%# <form action="offers"> %>
            <input type="radio" class="btn-check" name="filter" id="btnradio2" autocomplete="off">
            <%# <input type="hidden" name="filter" id="btnradio1" value="vegetarian"> %>
            <label class="btn btn-outline-dark" for="btnradio2">Vegetarian</label>
          <%# </form> %>

          <%# <form action="offers"> %>
            <input type="radio" class="btn-check" name="filter" id="btnradio3" autocomplete="off">
            <%# <input type="hidden" name="filter" id="btnradio1" value="flexible"> %>
            <label class="btn btn-outline-dark" for="btnradio3">Flexible</label>
          <%# </form> %>
        </div>
      </div>
  </div>

  <div class="filters-content">
    <h6>Pickup time</h6>
      <div class="checkboxes-container">
        <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">

        <%# <form action="offers"> %>
          <input type="checkbox" class="btn-check" name="filter" id="btncheck1" autocomplete="off">
          <%# <input type="hidden" name="filter" id="btnradio1" value="morning"> %>
          <label class="btn btn-outline-dark" for="btncheck1">Morning</label>
        <%# </form> %>

        <%# <form action="offers"> %>
          <input type="checkbox" class="btn-check" name="filter" id="btncheck2" autocomplete="off">
          <%# <input type="hidden" name="filter" id="btnradio1" value="afternoon"> %>
          <label class="btn btn-outline-dark" for="btncheck2">Afternoon</label>
        <%# </form> %>

        <%# <form action="offers"> %>
          <input type="checkbox" class="btn-check" name="filter" id="btncheck3" autocomplete="off">
          <%# <input type="hidden" name="filter" id="btnradio1" value="evening"> %>
          <label class="btn btn-outline-dark" for="btncheck3">Evening</label>
        <%# </form> %>
        </div>
      </div>
  </div>

  <div class="filters-content">
    <h6>Giver Type</h6>
      <div class="checkboxes-container">
        <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">

        <%# <form action="offers"> %>
          <input type="checkbox" class="btn-check" name="filter" id="btncheck4" autocomplete="off">
          <%# <input type="hidden" name="filter" id="btnradio1" value="organizations"> %>
          <label class="btn btn-outline-dark" for="btncheck4">Organizations</label>
        <%# </form> %>

        <%# <form action="offers"> %>
          <input type="checkbox" class="btn-check" name="filter" id="btncheck5" autocomplete="off">
          <%# <input type="hidden" name="filter" id="btnradio1" value="users"> %>
          <label class="btn btn-outline-dark" for="btncheck5">Users</label>
        <%# </form> %>
        </div>
      </div>
  </div>

  <div class="filters-content">
    <h6>Distance <span id="output"> 15 km</span></h6>
    <div class="checkboxes-container">
        <h6>1km</h6>
        <div class="slidecontainer">
          <input type="range" min="1" max="30" value="15" class="slider" id="myRange">
        </div>
        <h6>30+km</h6>
    </div>
  </div>


</div>