config/routes.rb
Rails.application.routes.draw do
  # get 'follows/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "offers#index"
  get "/map", to: "pages#map"
  get "/landing", to: "offers#landing"

  devise_for :users

  resources :chatrooms, only: %i[index show new create] do
    resources :messages, only: :create
  end

  resources :bookings, except: %i[new create] do
    resources :reviews
  end

  resources :offers do
    resources :bookings, only: %i[new create]
  end

  resources :dashboard, only: [:index] do
    resources :offers, only: %i[edit update destroy]
    resources :bookings, only: %i[edit update destroy]
    # patch 'offers/:id/update', to: 'dashboard#update_offer', as: :update_offer
    # delete 'offers/:id/delete', to: 'dashboard#delete_offer', as: :delete_offer
    patch 'bookings/:id/accept', to: 'dashboard#accept_booking', as: :accept_booking
    # patch 'bookings/:id/reject', to: 'dashboard#reject_booking', as: :reject_booking
    # patch 'bookings/:id/confirm', to: 'dashboard#confirm_booking', as: :confirm_booking
  end

  get "profiles/:id", to: "pages#profiles", as: 'profile'
  post 'profiles/:id', to: "pages#createprofile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/_info_window.html.erb
<div class="offercard-map">
  <%# main image display %>
  <div class= "img-container">
    <% if offer.images.attached? %>
      <% offer.images.each do |photo| %>
      <%= cl_image_tag photo.key,
        :gravity => "center",
        :width => 150,
        :height => 150,
        :effect=>"saturation:-25",
        :class => "offercard_image", crop: :fill %>
    <% end %>
    <% else %>
      <h5>PlaceHolder</h5>
    <% end %>
  </div>


  <%# user information %>
  <%= link_to offer  do%>
  <div class= "info-container">
    <%# offer information %>
    <div class="card-title">
        <div>
          <% if offer.bookings.empty? %>
          <span class = "offer-available"> Available <i class="fas fa-check-circle"></i> </span>
          <% else %>
          <span class = "offer-reserved"> Reserved <i class="fas fa-times-circle"></i> </span>
          <% end %>
        </div>
      <div>
        <strong><%= truncate(offer.title, length: 50) %></strong>
      </div>
    </div>

    <%# user information  %>
    <div class= "card-header">
        <div>
          <span class="username">@<%= offer.user.username %></span>
        </div>
        <span class="distance"><%= distance_km(current_user, offer) %>km <i class="bi bi-send"></i></span>
    </div>

  </div>
  <% end %>

</div>

app/views/pages/_marker.html.erb
<% if offer.images[0].present? %>
<%= cl_image_tag offer.images[0].key,
        :gravity => "center",
        :width => 50,
        :height => 50,
        :class => "avatar-bordered",
        crop: :fit %>
<% end %>

app/views/pages/_usermarker.html.erb
<% if user_avatar(User.find(offer.user_id)).present? %>
<%= cl_image_tag user_avatar(User.find(offer.user_id)),
        :gravity => "center",
        :class => "avatar-bordered",
        crop: :fill %>
<% end %>

app/views/pages/map.html.erb
<div
  class="map-index"
  data-controller="map"
  data-map-user-location ="<%= user_location_to_json() %>"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/pages/profiles.html.erb
<div class="first-profile-half mt-4">
    <%= cl_image_tag @user.profile_picture.key, class: "avatar-profile mt-3" %>

    <h3 class="mt-3">@<%= @user.username.capitalize %></h3>

  <% if Follow.find_by(followed_id:current_user.id)  %>
      <i class="fa-solid fa-check mt-3"></i>
  <% else %>
    <%= link_to profile_path(@user), data: {turbo_method: :post} do %>
      <i class="fa-regular fa-square-plus mt-3"></i>
    <% end %>
  <% end %>
</div>


<h1 class="mt-4" style="margin-left: 25px">Recent Posts</h1>

<div class="profiles-grid mt-3">

  <% @user.offers.each do  |offer| %>
    <%= link_to offer_path(offer.id) do %>
        <div class="post-card">
          <h6><%= truncate(offer.title, length: 10) %></h6>
          <%= cl_image_tag offer.images.first.key %>
        </div>
    <% end %>
  <% end %>
</div>